### ISSUE TITLE
EventHubCapture problem

### ISSUE THREAD

**Issue by mrmasterplan** [atc-net/atc-dataplatform#170]
I have noticed two major problems with the EventHubCapture class:
- the class does not work with direct access paths using a "abfss://" url as the table location. I have been unable to find our why this is, but my suspicion is that the SerDe classes that are called out do not support this mode.
- When trying the class with really large capture file collection, a simple read and display took 7.5 minutes. That is after the repair of the table had already taken place in a previous read. This is unacceptable.

I therefore propose that we use a different access mode, where all capture files are loaded directy with a spark.read.load call. This is something that was successfully done on this same capture file collection previously.

**Comment by LauJohansson** [comment]
@mrmasterplan is this closed now?
