### ISSUE TITLE
Create config python file with hardcoded strings

### ISSUE THREAD

**Issue by LauJohansson** [atc-net/atc-dataplatform#172]
For avoiding too many manual errors we could introduce a config variable file. E.g. instead of using ```TableConfigurator().get_property("name")``` then it is ```TableConfigurator().get_property(conf.NAME)```. 

conf.py:

```python
NAME = "name"
PARTITIONING="partitioning"
....
```

**Comment by LauJohansson** [comment]
constants.py file.

place under atc/

**Comment by mrmasterplan** [comment]
This is solved in #210 where you can generate just such a conf.py file from the configurator
