### ISSUE TITLE
TestSelectAndCastColumns is flaky

### ISSUE THREAD

**Issue by LauJohansson** [atc-net/atc-dataplatform#224]
I have experienced, that the test sometimes succeeds and sometimes dont:

https://github.com/atc-net/atc-dataplatform/actions/runs/3717255674/jobs/6304435074

It seems that the test data using datetime datatype is causing the issue.

**Comment by JeppeBlixen** [comment]
I will look into this

**Comment by JeppeBlixen** [comment]
This will be fixed in https://github.com/atc-net/atc-dataplatform/pull/233

**Comment by JeppeBlixen** [comment]
This is fixed in https://github.com/atc-net/atc-dataplatform/pull/233
