### ISSUE TITLE
Delta merge ignore no change

### ISSUE THREAD

**Issue by JeppeBlixen** [atc-net/atc-dataplatform#235]
The delta merge query should not write data, when a row is identical. The WHEN MATCHED clause should check if any changes have been made to any columns.

**Comment by LauJohansson** [comment]
https://github.com/atc-net/atc-dataplatform/blob/88edb01732310c46bae62f8e1b4f679b3bcd2450/src/atc/delta/delta_handle.py#L185

I think that this logic handles it? it finds only new records using the "CheckDfMerge" statement.

**Comment by JeppeBlixen** [comment]
I see, i wasn't aware of the that implementation using a join on the sink before the merge. I was thinking about adding it directly into the delta merge statement, but this properly have the same performance. Or maybe event better as it detects if only an append is necessary.

**Comment by LauJohansson** [comment]
I understand. That why it is good that you raised it as an issue. In that way can we knowledge share better!
