### ISSUE TITLE
Make it possible to save eventhub body as STRING

### ISSUE THREAD

**Issue by LauJohansson** [atc-net/atc-dataplatform#254]
Using Multi-hop/Medallion architecture - a bronze table should.

*"The Bronze layer is where we land all the data from external source systems. The table structures in this layer correspond to the source system table structures "as-is," along with any additional metadata columns that capture the load date/time, process ID, etc. The focus in this layer is quick Change Data Capture and the ability to provide an historical archive of source (cold storage), data lineage, auditability, reprocessing if needed without rereading the data from the source system."*

https://www.databricks.com/glossary/medallion-architecture

It should be possible to keep the json body as it is.

**Comment by mrmasterplan** [comment]
This sounds very reasonable actually. Let's discuss.
