### ISSUE TITLE
TableManager class

### ISSUE THREAD

**Issue by mrmasterplan** [atc-net/atc-dataplatform#34]
What we want:
- a singleton class
- that know all tables, including
  - their DB
  - name
  - path
  - type
  - schema
  - partitioning
- can be configured with SQL statements
- can be configured with pypark statements
- can automatically modify the path and name for release and debug usees
  - in release situation, the name and path are 'plain' i.e. close to the configured string, (minus markup)
  - in debug situations
    - the path changes to a `tmp` location
    - the name becomes something unique to allow parallel test runs
- can assert and validate the deployed properties and schemas
- can clean up and delete test tables

**Comment by LauJohansson** [comment]
@mrmasterplan - is this he same as the Table configurator?

**Comment by mrmasterplan** [comment]
no, not the same. I want this class to know all about the schema of the tables. I have considered this for a long time and have some partially working branches, but actually I think we should reject it for now. I think the complexity of the isse would take the interface too far from standard databricks. It would be a lot of work to maintain.
