### ISSUE TITLE
Dataframe Assertions

### ISSUE THREAD

**Issue by mrmasterplan** [atc-net/atc-dataplatform#35]
To assist unittest we want to be able to assert on the contents of dataframes.
Assertions may concern
- the column names
- the full schema (column names and types)
- the data contents of some, or all columns
- smart matching of some types
  - timestamps
    - handling of timeszones
    - approximate matching
-  ordered vs unordered matching

**Comment by LauJohansson** [comment]
Until then, one can convert the pyspark dataframe into a pandas dataframe - and then, use the pandas testing library: https://pandas.pydata.org/docs/reference/api/pandas.testing.assert_frame_equal.html.

**Comment by mrmasterplan** [comment]
dataframe assertions have been implemented in atc-dataplatform-tools
