### ISSUE TITLE
PR #54 broke my pipeline

### ISSUE THREAD

**Issue by mrmasterplan** [atc-net/atc-dataplatform#55]
Hi @JeppeBlixen and @christianhelle, the PR 54 that you merged had a non-compatible renaming in it:
`MultipleExtractOrchestrator` became `MultipleExtractorOrchestrator`. This broke our pipelines and our production system. Please reserve breaking changes and renaming for major version updates. I will now need to implement more careful dependency version control in my system. So actually thank you for bringing this to my attention :)

/rant

You can close the issue.

**Comment by JeppeBlixen** [comment]
Hi, i will change this back immediately. But thought are you not using the OrchestratorBuilder?
