### ISSUE TITLE
Drop support from python3.7 and spark 7.3

### ISSUE THREAD

**Issue by mrmasterplan** [atc-net/atc-dataplatform#76]
We intend to drop support for versions older than the latest LTS version in databricks. This mean dropping support for python 3.7 and spark version 7.3.x-scala2.1

A comment period has hereby started to give users the possibility to object. Unless substantial objections are received, we intend to end supporting these versions with the end of march 2022. 

A new major version will be set to mark this change.

**Comment by LauJohansson** [comment]
@mrmasterplan  - can we close this issue?
